'use client';

// Netopia NTPLogo wrapper (2026-06-10).
// Renders the official NETOPIA Payments + Visa + Mastercard combined logo
// using the merchant-bound component generated by Netopia's MediaKit panel
// (admin.netopia-payments.com/mediakit) for POS "HIRforYOU — Production"
// (secret=165813). This is a REQUIRED footer element for Netopia merchant
// approval — without it, the account verification is rejected (verified
// 2026-06-10 — first submission rejected with: "sigla NETOPIA pe care
// trebuie să o descarci din secțiunea Identitate vizuală... Sigla este un
// element obligatoriu în procesul de aprobare").
//
// Marked "use client" because the underlying ntp-logo-react package uses
// browser-only APIs (image rendering with computed colors) and cannot run
// during Next.js Server Components rendering.

import NTPLogo from 'ntp-logo-react';

/**
 * Official Netopia merchant logo for HIRforYOU Production POS.
 *
 * - `color="#ffffff"` tells the component the BACKGROUND it sits on is white,
 *   so the logo internally renders Netopia/Visa/Mastercard brand colors that
 *   are legible against white (matching our footer `bg-white`).
 * - `version="vertical"` was selected in the Netopia MediaKit panel.
 * - `secret="165813"` is the public merchant identifier for HIRforYOU Production
 *   (different from the signature key used for HMAC — this one is intentionally
 *   visible in the rendered logo for Netopia's verification).
 */
export function NetopiaLogo() {
  return <NTPLogo color="#ffffff" version="vertical" secret="165813" />;
}
