-- Lane INVENTORY-V1 (2026-05-06 evening) — additive schema for Premium-tier
-- inventory feature. Default OFF; opt-in per tenant via
-- tenants.feature_flags->>'inventory_enabled' = 'true'.
--
-- Tables (all RLS-enabled, all grant-locked):
--   1. inventory_items       — raw stock units per tenant (kg of flour, etc.)
--   2. menu_item_recipes     — many-to-many: which inventory_items are
--                              consumed when a menu_item is sold, qty per
--                              serving. Trigger (PR 3a) iterates this on
--                              order DELIVERED to deplete stock.
--   3. suppliers             — supplier directory (per tenant)
--   4. purchase_orders       — DRAFT generated by daily reorder cron (PR 3b);
--                              owner reviews then "sends" (PR 3c, deferred).
--   5. inventory_movements   — append-only ledger of every stock change.
--
-- Plus:
--   - tenants.feature_flags JSONB column (default '{}'), so this PR can ship
--     before the trigger PR and the trigger can no-op when the flag is false.
--
-- Distribution impact: Premium-tier upsell + AI-data-richness foundation.
-- Hepy orchestrator gains inventory awareness for forecasting / reorder /
-- waste detection. Brașov pilot opt-in, not required.
--
-- Idempotent: every CREATE/ALTER uses IF NOT EXISTS / IF EXISTS. Re-running
-- the migration is a no-op.

-- ============================================================
-- 0. tenants.feature_flags
-- ============================================================
alter table public.tenants
  add column if not exists feature_flags jsonb not null default '{}'::jsonb;

comment on column public.tenants.feature_flags is
  'Per-tenant feature gating. Keys are kebab-case-or-snake_case feature ids; values are boolean (or string for tiered features). Read in app via supabase select; write via OWNER admin UI. First key: inventory_enabled (Premium tier).';

-- ============================================================
-- 1. inventory_items
-- ============================================================
create table if not exists public.inventory_items (
  id                  uuid primary key default gen_random_uuid(),
  tenant_id           uuid not null references public.tenants(id) on delete cascade,
  name                text not null,
  unit                text not null
    check (unit in ('kg','g','l','ml','buc','portie')),
  current_stock       numeric(12,3) not null default 0,
  reorder_threshold   numeric(12,3) not null default 0,
  reorder_quantity    numeric(12,3) not null default 0,
  supplier_id         uuid,  -- FK added below after suppliers table created
  notes               text,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

create index if not exists idx_inventory_items_tenant
  on public.inventory_items(tenant_id);

create index if not exists idx_inventory_items_low_stock
  on public.inventory_items(tenant_id)
  where current_stock <= reorder_threshold;

alter table public.inventory_items enable row level security;

drop policy if exists inventory_items_member_read on public.inventory_items;
create policy inventory_items_member_read
  on public.inventory_items for select to authenticated
  using (
    exists (select 1 from public.tenant_members tm
             where tm.tenant_id = inventory_items.tenant_id
               and tm.user_id = auth.uid())
  );

-- writes go via service-role only (server actions in admin app)
revoke insert, update, delete, truncate, references, trigger
  on table public.inventory_items from anon;
revoke insert, update, delete, truncate, references, trigger
  on table public.inventory_items from authenticated;
revoke select on table public.inventory_items from anon;

comment on table public.inventory_items is
  'Raw stock units per tenant (Premium feature). Depleted by trigger on order DELIVERED via menu_item_recipes. RLS: tenant members read; service-role writes.';

-- ============================================================
-- 2. suppliers
-- ============================================================
create table if not exists public.suppliers (
  id           uuid primary key default gen_random_uuid(),
  tenant_id    uuid not null references public.tenants(id) on delete cascade,
  name         text not null,
  email        text,
  phone        text,
  notes        text,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create index if not exists idx_suppliers_tenant
  on public.suppliers(tenant_id);

alter table public.suppliers enable row level security;

drop policy if exists suppliers_member_read on public.suppliers;
create policy suppliers_member_read
  on public.suppliers for select to authenticated
  using (
    exists (select 1 from public.tenant_members tm
             where tm.tenant_id = suppliers.tenant_id
               and tm.user_id = auth.uid())
  );

revoke insert, update, delete, truncate, references, trigger
  on table public.suppliers from anon;
revoke insert, update, delete, truncate, references, trigger
  on table public.suppliers from authenticated;
revoke select on table public.suppliers from anon;

comment on table public.suppliers is
  'Supplier directory per tenant (Premium feature). Used by purchase_orders and inventory_items.supplier_id. RLS: tenant members read; service-role writes.';

-- inventory_items.supplier_id FK (deferred until suppliers exists)
do $$
begin
  if not exists (
    select 1 from information_schema.table_constraints
     where constraint_schema = 'public'
       and constraint_name = 'inventory_items_supplier_id_fkey'
  ) then
    alter table public.inventory_items
      add constraint inventory_items_supplier_id_fkey
      foreign key (supplier_id)
      references public.suppliers(id)
      on delete set null;
  end if;
end $$;

-- ============================================================
-- 3. menu_item_recipes
-- ============================================================
create table if not exists public.menu_item_recipes (
  id                   uuid primary key default gen_random_uuid(),
  tenant_id            uuid not null references public.tenants(id) on delete cascade,
  menu_item_id         uuid not null references public.restaurant_menu_items(id) on delete cascade,
  inventory_item_id    uuid not null references public.inventory_items(id) on delete cascade,
  qty_per_serving      numeric(12,4) not null check (qty_per_serving > 0),
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now(),
  unique (menu_item_id, inventory_item_id)
);

create index if not exists idx_menu_item_recipes_menu_item
  on public.menu_item_recipes(menu_item_id);

create index if not exists idx_menu_item_recipes_inventory_item
  on public.menu_item_recipes(inventory_item_id);

alter table public.menu_item_recipes enable row level security;

drop policy if exists menu_item_recipes_member_read on public.menu_item_recipes;
create policy menu_item_recipes_member_read
  on public.menu_item_recipes for select to authenticated
  using (
    exists (select 1 from public.tenant_members tm
             where tm.tenant_id = menu_item_recipes.tenant_id
               and tm.user_id = auth.uid())
  );

revoke insert, update, delete, truncate, references, trigger
  on table public.menu_item_recipes from anon;
revoke insert, update, delete, truncate, references, trigger
  on table public.menu_item_recipes from authenticated;
revoke select on table public.menu_item_recipes from anon;

comment on table public.menu_item_recipes is
  'Maps menu items → inventory items consumed per serving (Premium feature). PR 3a trigger iterates this on order DELIVERED to deplete stock. RLS: tenant members read; service-role writes.';

-- ============================================================
-- 4. purchase_orders
-- ============================================================
create table if not exists public.purchase_orders (
  id            uuid primary key default gen_random_uuid(),
  tenant_id     uuid not null references public.tenants(id) on delete cascade,
  supplier_id   uuid references public.suppliers(id) on delete set null,
  status        text not null default 'DRAFT'
    check (status in ('DRAFT','SENT','RECEIVED','CANCELLED')),
  items         jsonb not null default '[]'::jsonb,
  notes         text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  sent_at       timestamptz,
  received_at   timestamptz
);

create index if not exists idx_purchase_orders_tenant_status
  on public.purchase_orders(tenant_id, status);

create index if not exists idx_purchase_orders_supplier
  on public.purchase_orders(supplier_id);

alter table public.purchase_orders enable row level security;

drop policy if exists purchase_orders_member_read on public.purchase_orders;
create policy purchase_orders_member_read
  on public.purchase_orders for select to authenticated
  using (
    exists (select 1 from public.tenant_members tm
             where tm.tenant_id = purchase_orders.tenant_id
               and tm.user_id = auth.uid())
  );

revoke insert, update, delete, truncate, references, trigger
  on table public.purchase_orders from anon;
revoke insert, update, delete, truncate, references, trigger
  on table public.purchase_orders from authenticated;
revoke select on table public.purchase_orders from anon;

comment on table public.purchase_orders is
  'Reorder DRAFTs generated by daily inventory cron (PR 3b). Owner reviews and triggers send-to-supplier (PR 3c, deferred). items jsonb shape: [{inventory_item_id, name, qty, unit}]. RLS: tenant members read; service-role writes.';

-- ============================================================
-- 5. inventory_movements (append-only ledger)
-- ============================================================
create table if not exists public.inventory_movements (
  id                   uuid primary key default gen_random_uuid(),
  tenant_id            uuid not null references public.tenants(id) on delete cascade,
  inventory_item_id    uuid not null references public.inventory_items(id) on delete cascade,
  delta                numeric(12,3) not null,
  reason               text not null
    check (reason in ('ORDER_DELIVERED','MANUAL_ADJUST','PURCHASE_RECEIVED','WASTE','INITIAL_STOCK')),
  order_id             uuid,
  actor_user_id        uuid,
  metadata             jsonb not null default '{}'::jsonb,
  created_at           timestamptz not null default now()
);

create index if not exists idx_inventory_movements_tenant_created
  on public.inventory_movements(tenant_id, created_at desc);

create index if not exists idx_inventory_movements_item_created
  on public.inventory_movements(inventory_item_id, created_at desc);

create index if not exists idx_inventory_movements_order
  on public.inventory_movements(order_id)
  where order_id is not null;

alter table public.inventory_movements enable row level security;

drop policy if exists inventory_movements_member_read on public.inventory_movements;
create policy inventory_movements_member_read
  on public.inventory_movements for select to authenticated
  using (
    exists (select 1 from public.tenant_members tm
             where tm.tenant_id = inventory_movements.tenant_id
               and tm.user_id = auth.uid())
  );

revoke insert, update, delete, truncate, references, trigger
  on table public.inventory_movements from anon;
revoke insert, update, delete, truncate, references, trigger
  on table public.inventory_movements from authenticated;
revoke select on table public.inventory_movements from anon;

comment on table public.inventory_movements is
  'Append-only ledger of every stock change (Premium feature). Written by PR 3a trigger (delta<0, reason=ORDER_DELIVERED, order_id set), purchase receive flow, manual adjust UI, waste UI. RLS: tenant members read; service-role writes only.';

-- ============================================================
-- 6. updated_at triggers (reuse existing helper)
-- ============================================================
-- Reuse the canonical public.touch_updated_at() helper (already used by
-- restaurant_orders et al). Wrapped in DO block so the migration is still
-- a soft no-op if a future refactor renames the helper.
do $$
begin
  if exists (select 1 from pg_proc p join pg_namespace n on p.pronamespace = n.oid
              where n.nspname = 'public' and p.proname = 'touch_updated_at') then
    if not exists (select 1 from pg_trigger where tgname = 'trg_inventory_items_updated_at') then
      execute 'create trigger trg_inventory_items_updated_at before update on public.inventory_items for each row execute function public.touch_updated_at()';
    end if;
    if not exists (select 1 from pg_trigger where tgname = 'trg_suppliers_updated_at') then
      execute 'create trigger trg_suppliers_updated_at before update on public.suppliers for each row execute function public.touch_updated_at()';
    end if;
    if not exists (select 1 from pg_trigger where tgname = 'trg_menu_item_recipes_updated_at') then
      execute 'create trigger trg_menu_item_recipes_updated_at before update on public.menu_item_recipes for each row execute function public.touch_updated_at()';
    end if;
    if not exists (select 1 from pg_trigger where tgname = 'trg_purchase_orders_updated_at') then
      execute 'create trigger trg_purchase_orders_updated_at before update on public.purchase_orders for each row execute function public.touch_updated_at()';
    end if;
  end if;
end $$;
