-- ============================================================
-- ops-settings: max_parallel_orders + dispatch_mode + tenant_display_pins
-- decision: decision_courier_ops_dodo_pattern_2026-05-22
--
-- Depended upon by: feat/admin-control-room, feat/tablet-display-mode,
--                   feat/courier-mobile-pool
--
-- pgcrypto is already enabled (see 20260425_000_initial.sql).
-- ============================================================

-- ============================================================
-- 1. courier_profiles.max_parallel_orders
-- ============================================================
alter table public.courier_profiles
  add column if not exists max_parallel_orders int
    check (max_parallel_orders is null or max_parallel_orders between 1 and 10);

comment on column public.courier_profiles.max_parallel_orders is
  'Max comenzi paralele asignate simultan curierului. NULL = unlimited. Configurat din Control Room de Iulian individual per curier.';

-- ============================================================
-- 2. tenants.dispatch_mode  →  enum dispatch_mode_enum
--
-- The column already exists as:
--   dispatch_mode text not null default ''MANUAL''
--   check (dispatch_mode in (''MANUAL'',''AUTO''))
--
-- Migration strategy:
--   a. Create the new enum type (idempotent guard).
--   b. Drop the old check constraint (found by name in pg_constraint;
--      guarded so re-runs are safe).
--   c. Cast the column to the new enum, mapping:
--        ''MANUAL'' → ''MANUAL_PUSH''   (explicit manual assignment)
--        ''AUTO''   → ''HYBRID''        (self-pickup + 5-min safety net)
--   d. Set the new default.
-- ============================================================
do $$ begin
  if not exists (select 1 from pg_type where typname = 'dispatch_mode_enum') then
    create type public.dispatch_mode_enum as enum ('MANUAL_PUSH', 'SELF_PICKUP', 'HYBRID');
  end if;
end $$;

do $$
declare
  v_constraint text;
begin
  -- Find and drop any check constraint on tenants.dispatch_mode.
  -- The constraint name is generated by Postgres (tenants_dispatch_mode_check)
  -- but we search by expression to be safe across Supabase instance variants.
  select conname into v_constraint
    from pg_constraint
   where conrelid = 'public.tenants'::regclass
     and contype = 'c'
     and pg_get_constraintdef(oid) like '%dispatch_mode%';

  if v_constraint is not null then
    execute format('alter table public.tenants drop constraint %I', v_constraint);
  end if;
end $$;

-- Cast existing text values to enum.
-- Using USING clause with a CASE so legacy ''AUTO'' rows map to HYBRID.
alter table public.tenants
  alter column dispatch_mode drop default,
  alter column dispatch_mode type public.dispatch_mode_enum
    using case dispatch_mode
            when 'MANUAL' then 'MANUAL_PUSH'::public.dispatch_mode_enum
            when 'AUTO'   then 'HYBRID'::public.dispatch_mode_enum
            else               'HYBRID'::public.dispatch_mode_enum
          end,
  alter column dispatch_mode set default 'HYBRID'::public.dispatch_mode_enum;

comment on column public.tenants.dispatch_mode is
  'Mod de dispatch pentru curieri. MANUAL_PUSH = Iulian/dispatcher asignează manual. SELF_PICKUP = curierii își iau singuri (modelul Dodo). HYBRID = self-pickup cu safety net 5min după care alert dispatcher. Default HYBRID (decision 2026-05-22).';

-- ============================================================
-- 3. tenant_display_pins  (PIN tabletă kiosk în locație)
-- ============================================================
create table if not exists public.tenant_display_pins (
  tenant_id    uuid primary key references public.tenants(id) on delete cascade,
  pin_hash     text not null,    -- bcrypt hash via pgcrypto crypt(); NEVER plain text
  label        text,             -- ex: "Tabletă bucătărie"
  active       boolean not null default true,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  last_used_at timestamptz
);

comment on table public.tenant_display_pins is
  'PIN-uri pentru autentificare tabletă kiosk în locație (`/display/[tenantSlug]`). Un PIN per tenant pentru MVP; multi-PIN per locație vine în v2.';

-- RLS: enable but expose NOTHING directly — all access via RPCs below.
alter table public.tenant_display_pins enable row level security;

-- Service-role bypasses RLS by default in Supabase — no explicit policy needed.
-- Authenticated and anon get zero direct access; all reads go through verify_display_pin().
-- (No policy = deny-all for authenticated/anon.)

-- ============================================================
-- 4. RPC verify_display_pin(tenant_slug, pin_input)
-- ============================================================
create or replace function public.verify_display_pin(p_tenant_slug text, p_pin text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_pin_hash  text;
  v_tenant_id uuid;
begin
  select t.id, tdp.pin_hash
    into v_tenant_id, v_pin_hash
   from public.tenants t
   join public.tenant_display_pins tdp on tdp.tenant_id = t.id
  where t.slug = p_tenant_slug
    and tdp.active = true;

  if v_pin_hash is null then
    return false;
  end if;

  if v_pin_hash = crypt(p_pin, v_pin_hash) then
    update public.tenant_display_pins
       set last_used_at = now()
     where tenant_id = v_tenant_id;
    return true;
  end if;

  return false;
end;
$$;

grant execute on function public.verify_display_pin(text, text) to anon, authenticated;

-- ============================================================
-- 5. RPC set_display_pin(tenant_id, new_pin)
--    Called only by service-role (admin UI / backend). Hashes before storing.
-- ============================================================
create or replace function public.set_display_pin(p_tenant_id uuid, p_new_pin text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.tenant_display_pins (tenant_id, pin_hash, active)
  values (p_tenant_id, crypt(p_new_pin, gen_salt('bf')), true)
  on conflict (tenant_id) do update
    set pin_hash    = excluded.pin_hash,
        active      = true,
        updated_at  = now();
end;
$$;

-- Intentionally NOT granted to anon/authenticated — service-role only.
-- Postgres grants EXECUTE to PUBLIC by default on new functions in `public`,
-- so we must revoke from PUBLIC explicitly. Revoking only from anon/authenticated
-- leaves the SECURITY DEFINER RPC callable, which would let any client reset
-- arbitrary tenant PINs.
revoke execute on function public.set_display_pin(uuid, text) from public;
revoke execute on function public.set_display_pin(uuid, text) from anon, authenticated;

-- ============================================================
-- 6. Seed demo PIN 1234 for deliveryhouse tenant
--    Safe no-op if tenant does not exist yet.
-- ============================================================
do $$
declare
  v_tenant_id uuid;
begin
  select id into v_tenant_id from public.tenants where slug = 'deliveryhouse';

  if v_tenant_id is null then
    raise notice 'Tenant "deliveryhouse" not found — skipping demo PIN seed.';
    return;
  end if;

  insert into public.tenant_display_pins (tenant_id, pin_hash, label)
  values (v_tenant_id, crypt('1234', gen_salt('bf')), 'Tabletă demo deliveryhouse')
  on conflict (tenant_id) do nothing;
end $$;
